apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: bharat9838/flask-app:v1.0.1
        ports:
        - containerPort: 5050  
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5050
          initialDelaySeconds: 15
          periodSeconds: 20
