apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: flaskapp  # Add this to match the Deployment namespace
spec:
  selector:
    app: myapp
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
  type: ClusterIP  # Default type; you can change to LoadBalancer or NodePort if needed
