apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: flaskapp  
spec:
  selector:
    app: myapp
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
  type: ClusterIP 
